"""first migration

Revision ID: 8fcfe27de82c
Revises: 
Create Date: 2022-06-10 04:42:06.404926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcfe27de82c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=False, default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.drop_column('default')

    # ### end Alembic commands ###
